#output_dir: /nfs/diskstation/projects/mech_search/prob_pose/benchmark_results_soft
output_dir: benchmark_results_soft
save_conf_name: config.yaml

model:
  path: models/fcn_lr1e-420191205_172828.246862
  #path: /nfs/diskstation/projects/mech_search/prob_pose/models/fcn_lr1e-420191205_172828.246862
  gpu: 1
  batch_size: 8

dataset:
  soft_masks: 1
  path: /home/mjd3/pose/probabilistic-poses/datasets/dataset_test_11_21/images
  #path: /nfs/diskstation/projects/mech_search/prob_pose/datasets/dataset_test_11_21/images
  max_inds: 32 # 0 if no limit, otherwise the maximum number of images to test on (for debugging)

# Visualization settings
vis: 0
vis_interval: 10
