output_dir: benchmark
scale: 1

model:
  path: models/xray_model
  device: cuda:0
  batch_size: 16

dataset:
  path: datasets/example_dataset
  imgs: 'combo_ims'
  lbls: 'dist_ims'
  mean: [180.614705, 180.614705, 0.0624726135]
  max_ind: 0

# Visualization settings
viz: 1
viz_block: 1
viz_interval: 10
