output_dir: benchmark/test
save_conf_name: config.yaml
scale: 1

model:
  type: fcn
  path: models/test
  # ratios: [1,2,3,5,10]
  ratios: null
  gpu: 1
  batch_size: 16

dataset:
  path: /home/mjd3/working/laxray/laxray-sim/datasets/dist_dataset
  imgs: 'depth'
  lbls: 'dist'
  mean: [101.46017946, 101.46017946, 101.46017946]
  max_ind: 0

# Visualization settings
vis: 1
vis_block: 1
vis_interval: 10
