output_dir: ./benchmark/1_channel_sem_8-29
save_conf_name: config.yaml
scale: 1

model:
  type: fcn
  path: models/1_channel_sem_8-29
  ratios: [1]
  gpu: 0
  batch_size: 1

dataset:
  # path: ./ratio_dataset/images/
  # path: ./lateral_data/images
  path: /home/memo/Documents/Berk_Research/probabilistic-poses/dataset_imgs/
  #imgs: 'combo_ims'
  #lbls: 'dist_ims'
  imgs: 'train_ims'
  lbls: 'soft_dist_ims'
  mean: [179.8, 179.8, 0]

# Visualization settings
vis: 1
vis_block: 1
vis_interval: 1
