output_dir: /nfs/diskstation/projects/mech_search/prob_pose/benchmark_results/benchmark_2d/box_10
save_conf_name: config.yaml

model:
  type: fcn
  path: /nfs/diskstation/projects/mech_search/prob_pose/models/2d_models/box_10_fcn_01_27_lr1e-420200128_113502.898478/
  gpu: 1
  batch_size: 8

dataset:
  path: /nfs/diskstation/projects/mech_search/prob_pose/datasets/2d_datasets/single_goal_datasets/box_10_soft_dataset/images/
  imgs: 'color_ims'
  # targs: 'target_ims_test'
  lbls: 'soft_dist_ims'

# Visualization settings
vis: 1
vis_interval: 10
