output_dir: /nfs/diskstation/projects/mech_search/prob_pose/benchmark_results/benchmark_multi/benchmark_ar1_flat_lid/
save_conf_name: config.yaml
scale: 2

model:
  type: fcn
  path: /nfs/diskstation/projects/mech_search/prob_pose/models/single_goal_rotations/box_1_r16_fine_fcn_2_620200206_183634.222720/
  gpu: 0
  batch_size: 8

dataset:
  path: /nfs/diskstation/projects/mech_search/prob_pose/datasets/soft_single_goal_datasets/flat_lid_test_only_dataset/images/
  imgs: 'color_ims'
  # targs: 'target_ims'
  lbls: 'soft_dist_ims'

# Visualization settings
vis: 1
vis_interval: 3
