output_dir: /nfs/diskstation/projects/mech_search/prob_pose/benchmark_results/benchmark_multi/benchmark_5_target
save_conf_name: config.yaml

model:
  type: siamese_fcn
  path: /nfs/diskstation/projects/mech_search/prob_pose/models/5_target_r16_siamese_fcn_2_820200208_232932.399756/
  gpu: 1
  batch_size: 8

dataset:
  path: /nfs/diskstation/projects/mech_search/prob_pose/datasets/multi_goal_datasets/5_target_r16_dataset/images
  imgs: 'color_ims'
  targs: 'target_ims'
  lbls: 'soft_dist_ims'

# Visualization settings
vis: 1
vis_interval: 10
