output_dir: benchmark/test
save_conf_name: config.yaml
scale: 1

model:
  type: fcn
  path: models/test_test
  ratios: [1,2,3,5,10]
  gpu: 1
  batch_size: 4

dataset:
  path: /home/mjd3/working/pose/sd-maskrcnn/datasets/ratio_dataset/images/
  imgs: 'combo_ims'
  lbls: 'dist_ims'
  mean: [179.8, 179.8, 0]

# Visualization settings
vis: 1
vis_block: 1
vis_interval: 10
