output_dir: /benchmark
scale: 1

model:
  path: /models/my_model_docker
  device: cuda:1
  batch_size: 16

dataset:
  path: /dataset
  imgs: 'combo_ims'
  lbls: 'dist_ims'
  mean: [180.614705, 180.614705, 0.0624726135]
  max_ind: 0

# Visualization settings
viz: 1
viz_block: 1
viz_interval: 10
