model:
  name: sss_model
  path: models
  ratios: [0, 1, 2]
  epochs: 100
  device: cuda:0
  batch_size: 8
  lr: 1e-4
  momentum: 0.99
  weight_decay: 0.0005

dataset:
  num_workers: 0
  path: /home/qingh097/slaxray/laxray-sim/dataset/d445_dataset_10000
  imgs: 'depth'
  lbls: 'dist'
  mean: [180.614705, 180.614705, 0.0624726135]
  max_ind: 0
