# model:
#   name: test_test
#   path: models/
#   type: fcn
#   ratios: [1,2,3,5,10]
#   max_iteration: 50000       # number of epochs to train for
#   gpu: 0
#   batch_size: 8
#   lr: 1e-4
#   momentum: 0.99
#   weight_decay: 0.0005

# dataset:
#   path: ./training_datasets/box_1/
#   imgs: 'train_ims'
#   lbls: 'label_ims'
#   mean: [179.8, 179.8, 0]
#   max_ind: 1000

# # name of the config file to save (within the dataset folder)
# # note that this will be overwritten between multiple runs so
# # you should name this uniquely for each run.
# save_conf_name: test.yaml

model:
  name: 1_channel_sem_8-29
  path: models/
  type: fcn
  # ratios: [1,2,3,5,10]
  ratios: [1]
  # max_iteration: 50000       # number of epochs to train for
  max_iteration: 500
  gpu: 0
  batch_size: 16
  lr: 1e-4
  momentum: 0.99
  weight_decay: 0.0005

dataset:
  #path: ./lateral_data/images
  path: /home/memo/Documents/Berk_Research/probabilistic-poses/dataset_imgs/
  #imgs: 'combo_ims'
  imgs: 'train_ims'
  #lbls: 'dist_ims'
  lbls: 'soft_dist_ims'
  mean: [179.8, 179.8, 0]
  max_ind: 0

# name of the config file to save (within the model folder)
save_conf_name: 1_channel.yaml
